FROM python:3.13-slim

WORKDIR /app

COPY client/requirements.txt ./

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY client .

EXPOSE 8501

CMD ["streamlit", "run", "app.py"]